<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EphChartbeat\Module'                => __DIR__ . '/Module.php',
    'EphChartbeat\Options\ModuleOptions' => __DIR__ . '/src/EphChartbeat/Options/ModuleOptions.php',
    'EphChartbeat\View\Helper\Chartbeat' => __DIR__ . '/src/EphChartbeat/View/Helper/Chartbeat.php',
);